apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          imagePullPolicy: IfNotPresent
          image: docker.io/soumikdutta/gateway:1
          command: ["java", "-jar", "gateway.jar", "0.0.0.0:8080"]
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"