apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demoservice
  labels:
    app: demoservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demoservice
  template:
    metadata:
      labels:
        app: demoservice
    spec:
      containers:
        - name: demoservice
          imagePullPolicy: IfNotPresent
          image: docker.io/soumikdutta/demoservice:1
          command: ["java", "-jar", "demoservice.jar", "0.0.0.0:8081"]
          ports:
            - containerPort: 8081
          resources:
            limits:
              memory: "512Mi"